image: docker:19.03.0

stages:
  - build
  - test
  - release

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: docker-registry.kronova.net
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TEST_IMAGE: docker-registry.kronova.net/docker/typo3-utilities:latest
  CONTAINER_DOCKERHUB_LATEST: kronova/typo3-utilities
  CONTAINER_DOCKERHUB_TAG: kronova/typo3-utilities:$CI_COMMIT_TAG

services:
  - docker:19.03.0-dind

before_script:
  - echo "$CI_BUILD_TOKEN" | docker login --username gitlab-ci-token $DOCKER_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

# todo: add better tests
test-php:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE php -v
  only:
    - master

test-composer:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE composer -V
  only:
    - master

test-imagemagick:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE convert -version
  only:
    - master

test-rsync:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE rsync --version
  only:
    - master

test-deployer:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE dep --version
  only:
    - master

test-surf:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE surf --version
  only:
    - master

push-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DOCKERHUB_LATEST
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_LATEST
  only:
    - master
  allow_failure: false
  when: manual

push-tag-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DOCKERHUB_TAG
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_TAG
  only:
    - tags
