image: docker:19.03.0

stages:
  - build
  - test
  - release

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: docker-registry.kronova.net
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TEST_IMAGE: docker-registry.kronova.net/docker/typo3-utilities:latest
  CONTAINER_DOCKERHUB_LATEST: kronova/typo3-utilities
  CONTAINER_DOCKERHUB_TAG: kronova/typo3-utilities:$CI_COMMIT_TAG

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./.build

services:
  - docker:19.03.0-dind

before_script:
  - echo "$CI_BUILD_TOKEN" | docker login --username gitlab-ci-token $DOCKER_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    # todo: remove the gitlab container registry completely and use docker hub only
    - docker push $CONTAINER_TEST_IMAGE
    - mkdir -p ./.build
    - docker save $CONTAINER_TEST_IMAGE -o ./.build/image.tar
  only:
    - master

.test:
  stage: test
  before_script:
    # use gitlab-ci cache instead of container registry to bypass the slow pull
    - docker load < ./.build/image.tar || true
  only:
    - master

test-php:
  extends: .test
  script:
    - docker load < ./.build/image.tar || true
    - docker run $CONTAINER_TEST_IMAGE php -v

test-typo3_8:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE composer require typo3/minimal '^8'

test-typo3_9:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE composer require typo3/minimal '^9'

test-typo3_10:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE composer require typo3/minimal '^10'

test-imagemagick:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE convert -version

test-rsync:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE rsync --version
  only:
    - master

test-deployer:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE dep --version

test-surf:
  extends: .test
  script:
    - docker run $CONTAINER_TEST_IMAGE surf --version

push-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DOCKERHUB_LATEST
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_LATEST
  only:
    - master
  allow_failure: false
  when: manual

push-tag-on-dockerhub:
  stage: release
  before_script: []
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DOCKERHUB_TAG
    - docker logout
    - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
    - docker push $CONTAINER_DOCKERHUB_TAG
  only:
    - tags
